[package]
name = "harriet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory = "0.3.2"
nom = { version = "6.2.1", features = ["alloc"]}
