on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Should be kept in sync with MSRV specified in Cargo.toml
          toolchain: 1.65.0
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
